[uwsgi]
module = app
callable = application

master = true
processes = 4
threads = 2
http = 0.0.0.0:8090

die-on-term = true
enable-threads = true
lazy-apps = true
buffer-size = 65535
harakiri = 60

logto = /dev/stdout
log-4xx = true
log-5xx = true